### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by das-g** [bpeel/prevodb#2]
I'd like to package this software for a Linux distribution. I _can_ make the package definition refer to a specific Git revision by commit hash, but it'd be much nicer if it instead refers to a proper upstream version number and a corresponding Git tag.

**Comment by bpeel** [comment]
That would be great if you are able to package prevodb. I am planning to make a release of the Android app soon which includes changes to prevodb. After testing it a bit I will tag the commit of prevodb used to make the app. Thanks for looking into this.

**Comment by bpeel** [comment]
I made the [release](https://github.com/bpeel/prevodb/releases/tag/0.2). Thanks.
