### ISSUE TITLE
feature request: allow to search for non-Esperanto words

### ISSUE THREAD

**Issue by das-g** [bpeel/prevodb#4]
When using a dictionary, I often want to look up the Esperanto term(s) for a word in my native language or some other third language. It'd be cool if this was possible on the command line using `prevo`.

The default should probably remain to interpret the non-option argument as an Esperanto word to look up. One possible user interface would be a command line flag per non-Esperanto language that indicates what language the input is supposed to be. I'd suggest to make them long options and use 2-letter ISO language codes.

So
```bash
prevo domo
```
would still look up the Esperanto word "domo". And

```bash
prevo --de Haus
```
would look up the German word "Haus" (and thus hopefully also display the article for "domo").

**Comment by bpeel** [comment]
You can specify the language code of the language to search in by giving a second non-option argument, like this:

    prevo de Haus

This is mentioned in the README and the `--help` but admittedly it’s not very obvious.

Thanks anyway for the suggestion.

**Comment by das-g** [comment]
Oops, should have read the README and `--help` text more carefully. Sorry for the noise.
