### ISSUE TITLE
data search path

### ISSUE THREAD

**Issue by das-g** [bpeel/prevodb#5]
If I keep the database at `~/.local/share/prevo/prevo.db`, `prevo` uses it automatically when no `-d` option is used.

- Are there other places where `prevo` looks for it when no `-d` option has been passed?
- Can the search path(s) be influenced somehow without recompiling?

Context: If I package the database for a Linux distribution, it would off course be installed at some system-wide location, not in the current user's home. It'd be good if the user wouldn't have to specify it with `-d` unless they want to override the behavior and use a different DB.

**Comment by bpeel** [comment]
> Are there other places where prevo looks for it when no -d option has been passed?

prevo looks in all of the directories returned by `g_get_user_data_dir` and [`g_get_system_data_dirs`](https://developer.gnome.org/glib/2.28/glib-Miscellaneous-Utility-Functions.html#g-get-system-data-dirs). In practice that means you probably want to install the file at `/usr/share/prevo/prevo.db`.

> Can the search path(s) be influenced somehow without recompiling?

`g_get_system_data_dirs` uses the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) to specify the search path. That effectively means you can influence it by setting `XDG_DATA_DIRS`.
