### ISSUE TITLE
Necesas akordigi la elŝutadon de Revo-fontoj

### ISSUE THREAD

**Issue by wdiestel** [bpeel/prevodb#6]
La fonto-dosieroj de Revo ne plu aktualiĝas sub /tgz/, sed necesas ilin elŝuti el la ĉiutagaj eldonoj ĉe Github:
https://github.com/revuloj/revo-fonto/releases/latest

Kiel ekzemplon vi povas uzi [tiun elŝuto-skripton](https://github.com/revuloj/voko-araneo/blob/master/bin/revo_download_gh.sh).

**Comment by bpeel** [comment]
La README-dokumentoj de prevodb kaj prevo nun rekomendas rekte kloni la deponejojn de revo-fonto kaj voko-grundo, do mi supozas ke oni povas konsideri ĉi tiun raporton solvita.
